<?php

use Drupal\Core\Hook\Attribute\LegacyModuleImplementsAlter;

/**
 * @file
 * Functionality for admin / editor UX.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\dpl_admin\Hook\ContentLockHooks;
use Drupal\dpl_admin\Hook\FormHooks;
use Drupal\dpl_admin\Hook\MenuHooks;
use Drupal\dpl_admin\Hook\SystemHooks;
use Drupal\dpl_admin\Hook\ThemeHooks;
use Drupal\dpl_admin\Hook\ToolbarHooks;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/*
 * The following hook function is for Drupal 10, it can be removed, together
 * with the hook class service in `dpl_admin.services.yml` when upgrading to
 * Drupal 11.
 */

/**
 * Implements hook_local_tasks_alter().
 *
 * @param array<mixed> $local_tasks
 *   See the $form in hook_local_tasks_alter().
 */
#[LegacyHook]
function dpl_admin_local_tasks_alter(array &$local_tasks): void {
  \Drupal::service(MenuHooks::class)->localTasksAlter($local_tasks);
}

/**
 * Implements hook_menu_local_actions_alter().
 *
 * @param array<mixed> $local_actions
 *   See the $form in hook_local_actions_alter().
 */
#[LegacyHook]
function dpl_admin_menu_local_actions_alter(&$local_actions) : void {
  \Drupal::service(MenuHooks::class)->menuLocalActionsAlter($local_actions);
}

/**
 * Implements template_preprocess_views_view_field().
 *
 * @phpstan-ignore missingType.iterableValue (variables too complex)
 */
#[LegacyHook]
function dpl_admin_preprocess_views_view_field(array &$variables): void {
  \Drupal::service(ThemeHooks::class)->preprocessViewsViewField($variables);
}

/**
 * Implements template_preprocess_html().
 */
#[LegacyHook]
function dpl_admin_preprocess_html(array &$variables): void {
  \Drupal::service(ThemeHooks::class)->preprocessHtml($variables);
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure the dpl_admin form_alter happens last, after any other contrib
 * modules. This is necessary for us to alter the password policy position.
 *
 * It's obsoleted in D11.2, the hook attribute can provide ordering.
 */
#[LegacyModuleImplementsAlter]
function dpl_admin_module_implements_alter(array &$implementations, string $hook): void {
  if ($hook == 'form_alter') {
    $group = $implementations['dpl_admin'];
    unset($implementations['dpl_admin']);
    $implementations['dpl_admin'] = $group;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add basic styling classes to the "reset password" page, as it does not
 * have any Gin styling.
 */
#[LegacyHook]
function dpl_admin_form_user_pass_reset_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  \Drupal::service(FormHooks::class)->formUserPassResetAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_alter().
 *
 * Alter the edit/add forms for eventseries/event instances.
 *
 * @param array<mixed> $form
 *   See the $form in hook_form_alter().
 */
#[LegacyHook]
function dpl_admin_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  \Drupal::service(FormHooks::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_element_info_alter().
 *
 * Override the datetime element, to remove seconds input.
 *
 * @param array<mixed> $types
 *   See the $types in hook_element_info_alter().
 */
#[LegacyHook]
function dpl_admin_element_info_alter(array &$types): void {
  \Drupal::service(SystemHooks::class)->elementInfoAlter($types);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
#[LegacyHook]
function dpl_admin_menu_link_content_presave(MenuLinkContent $entity): void {
  \Drupal::service(MenuHooks::class)->menuLinkContentPresave($entity);
}

/**
 * Implements hook_dpl_protected_nodes_get_protected_nodes().
 */
#[LegacyHook]
function dpl_admin_dpl_protected_nodes_get_protected_nodes(): array {
  return \Drupal::service(SystemHooks::class)->dplProtectedNodesGetProtectedNodes();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array<mixed> $form
 *   The form array.
 */
#[LegacyHook]
function dpl_admin_form_node_confirm_form_alter(array &$form, FormStateInterface $form_state): void {
  \Drupal::service(ContentLockHooks::class)->alterDeleteConfirmForm($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array<mixed> $form
 *   The form array.
 */
#[LegacyHook]
function dpl_admin_form_taxonomy_term_confirm_form_alter(array &$form, FormStateInterface $form_state): void {
  \Drupal::service(ContentLockHooks::class)->alterDeleteConfirmForm($form, $form_state);
}

/**
 * Implements hook_toolbar_alter().
 *
 * Displaying the DPL CMS version in the secondary admin toolbar.
 *
 * @param array<mixed> $items
 *   See hook_toolbar_alter().
 */
#[LegacyHook]
function dpl_admin_toolbar_alter(array &$items): void {
  \Drupal::service(ToolbarHooks::class)->toolbarAlter($items);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Altering the form for EDITING (not creating) an event series.
 */
#[LegacyHook]
function dpl_admin_form_eventseries_default_edit_form_alter(array &$form, FormStateInterface $form_state): void {
  \Drupal::service(FormHooks::class)->formEventseriesDefaultEditFormAlter($form, $form_state);
}
