<?php

declare(strict_types=1);

namespace Drupal\dpl_po;

use Psr\Log\LoggerInterface;
use function Safe\preg_replace;

/**
 * Turns what potx collected into the .po file we hand to POEditor.
 *
 * What potx produces is a template meant for localize.drupal.org, and it has a
 * couple of habits that leave a file gettext will not read. This is the work
 * that sits between the two. It is kept out of the Drush command so it can be
 * tested without a Drupal installation and a database of translations.
 */
class PoFileBuilder {

  /**
   * Class constructor.
   *
   * @param \Psr\Log\LoggerInterface $logger
   *   Where to report the corrections made along the way.
   */
  public function __construct(
    protected LoggerInterface $logger,
  ) {}

  /**
   * Drop plain strings that a plural string already defines.
   *
   * Potx keys a plural string by its singular and plural form together, and a
   * plain string by itself, so "1 month" from a formatPlural() call and
   * "1 month" from a t() call are two entries to potx. A .po file identifies a
   * message by its context and singular alone, so the two come out as one
   * message defined twice, which gettext refuses.
   *
   * The plural entry is the one to keep - its first form is the singular
   * translation, so nothing is lost by dropping the plain one.
   *
   * No project in scanned_modules.txt collides today, but facets, purge,
   * recurring_events and webform all do, so adding one of those to the list
   * would break the scan without this.
   *
   * @param array<string, array<string, mixed>> $strings
   *   Potx' collected strings, keyed by string and then by context.
   *
   * @return array<string, array<string, mixed>>
   *   The same, without the plain strings a plural string already defines.
   */
  public function removeShadowedPlurals(array $strings): array {
    $dropped = 0;
    foreach ($strings as $string => $contexts) {
      // Potx delimits the singular and plural form with a null byte.
      if (!str_contains((string) $string, "\0")) {
        continue;
      }

      [$singular] = explode("\0", (string) $string);
      foreach (array_keys($contexts) as $context) {
        if (isset($strings[$singular][$context])) {
          unset($strings[$singular][$context]);
          $dropped++;
        }
      }

      if (isset($strings[$singular]) && empty($strings[$singular])) {
        unset($strings[$singular]);
      }
    }

    if ($dropped > 0) {
      $this->logger->info(sprintf('Dropped %d plain strings that a plural string already defines.', $dropped));
    }

    return $strings;
  }

  /**
   * Turn what potx built into the contents of a .po file.
   *
   * This is potx' own _potx_write_files(), which we cannot use as it writes to
   * a hardcoded file name in the current directory, plus the adjustments we
   * need for the file we hand to POEditor.
   *
   * @param array{header: string, strings: string} $built
   *   One entry of the potx output store.
   *
   * @return string
   *   The contents of the .po file. Writing it is left to the caller.
   */
  public function render(array $built): string {
    $header = $built['header'];

    // Potx leaves a placeholder in the header for a list of the files it found
    // strings in, meant for recording module versions when publishing a
    // template to localize.drupal.org. We scan a git checkout, so every entry
    // would read "n/a" - a thousand lines of noise that churn whenever a file
    // moves. Say where the file came from instead.
    $header = str_replace('--VERSIONS--', 'Generated by "drush dpl_po:scan-source". Do not edit by hand.', $header);

    // Potx marks the header fuzzy, which is the convention for a template. What
    // we produce is a complete translation file. The header is the only place
    // potx sets the flag, and the file is built from scratch on every run, so
    // there are no per-string flags to preserve.
    $header = str_replace("#, fuzzy\n", '', $header);

    // Drop the "#:" source references. They would add thousands of lines to the
    // committed file and churn whenever code moves, and POEditor does not need
    // them - it identifies a string by its context and source text.
    $strings = preg_replace('/^#:[^\n]*\n/m', '', $built['strings']);

    return $header . $strings;
  }

}
