<?php

/**
 * @file
 * DPL Library Token module.
 *
 * Handles fetching and storage of a library token.
 */

use Drupal\dpl_library_token\LibraryTokenHandler;
use Drupal\drupal_typed\DrupalTyped;

/**
 * Implements hook_cron.
 */
function dpl_library_token_cron(): void {
  $handler = DrupalTyped::service(LibraryTokenHandler::class, 'dpl_library_token.handler');
  $handler->retrieveAndStoreToken();
}
