<?php

/**
 * @file
 * Primary module hooks for EO Next Event Engine.
 */

/**
 * Implements hook_modules_installed().
 */
function eonext_event_engine_modules_installed(array $modules, bool $is_syncing): void {
  if ($is_syncing || !in_array('eonext_event_engine', $modules, TRUE)) {
    return;
  }

  \Drupal::moduleHandler()->loadInclude('eonext_event_engine', 'install');
  eonext_event_engine_update_config();
}
