/**
 * wsiINST v6 — Institution lookup via STIL's Brugerdatabasen SOAP API.
 *
 * Authentication uses WS-Security with X.509 certificate signing (asymmetric binding).
 * Each request is signed with the provider's private key and includes:
 * - UdbydersystemId SOAP header (identifies the provider system)
 * - WS-Addressing headers (Action, To, MessageID)
 * - Timestamp (auto-generated by WSSecurityCert)
 *
 * Required env vars:
 *   UNILOGIN_WS_PRIVATE_KEY     — PEM-encoded private key (newlines as \n)
 *   UNILOGIN_WS_PUBLIC_CERT     — PEM-encoded public certificate (newlines as \n)
 *   UNILOGIN_WS_UDBYDERSYSTEM_ID — Provider system ID from STIL Tilslutning
 *
 * Certificate and UdbydersystemId are registered at https://tilslutning.stil.dk/
 */
import { randomUUID } from "crypto"
import { WSSecurityCert } from "soap"

import { getServerEnv } from "@/lib/config/env"
import { isTest } from "@/lib/config/environmentChecks"
import { createClientAsync } from "@/lib/soap/unilogin/wsiinst-v6/generated/ws"

import schemas from "./schemas"

const WSIINST_V6_URL = "https://brugerdatabasen.stil.dk/bpi/wsiinst/6"
const COMMON_V3_NAMESPACE = "https://brugerdatabasen.stil.dk/bpi/common/3"
const WSA_NAMESPACE = "http://www.w3.org/2005/08/addressing"

// The WSDL uses vendored XSDs (local schema references) to avoid remote fetches.
// The endpoint is set explicitly below for both test and production.
const isTestMode = isTest()
const clientEndpoint = isTestMode
  ? `${getServerEnv("UNILOGIN_WELLKNOWN_URL")}/institution`
  : WSIINST_V6_URL

export const getInstitutionRequest = async (institutionId: string) => {
  const client = await createClientAsync("./lib/soap/unilogin/wsiinst-v6/wsdl/ws.wsdl", {
    forceSoap12Headers: true,
    endpoint: clientEndpoint,
  })

  // In test mode the mock server doesn't enforce WS-Security, so skip signing.
  if (!isTestMode) {
    const privateKey = getServerEnv("UNILOGIN_WS_PRIVATE_KEY")?.replace(/\\n/g, "\n")
    const publicCert = getServerEnv("UNILOGIN_WS_PUBLIC_CERT")?.replace(/\\n/g, "\n")
    const udbydersystemId = getServerEnv("UNILOGIN_WS_UDBYDERSYSTEM_ID")

    if (!privateKey || !publicCert) {
      throw new Error("Missing Unilogin WS-Security certificate configuration")
    }

    if (!udbydersystemId) {
      throw new Error("Missing Unilogin UdbydersystemId (UNILOGIN_WS_UDBYDERSYSTEM_ID)")
    }

    const wsSecurity = new WSSecurityCert(privateKey, publicCert, undefined, {
      hasTimeStamp: true,
      signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
      digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256",
      additionalReferences: ["uni:UdbydersystemId", "wsa:Action", "wsa:To", "wsa:MessageID"],
      signerOptions: {
        prefix: "ds",
        existingPrefixes: {
          wsse: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",
        },
      },
    })
    client.setSecurity(wsSecurity)

    // Add UdbydersystemId SOAP header (must be signed per policy)
    client.addSoapHeader(
      `<uni:UdbydersystemId xmlns:uni="${COMMON_V3_NAMESPACE}">${udbydersystemId}</uni:UdbydersystemId>`
    )

    // Raw XML ensures the wsa namespace prefix is declared on each element.
    client.addSoapHeader(
      `<wsa:Action xmlns:wsa="${WSA_NAMESPACE}">${WSIINST_V6_URL}/hentInstitution</wsa:Action>` +
        `<wsa:To xmlns:wsa="${WSA_NAMESPACE}">${clientEndpoint}</wsa:To>` +
        `<wsa:MessageID xmlns:wsa="${WSA_NAMESPACE}">urn:uuid:${randomUUID()}</wsa:MessageID>`
    )
  }

  const [response] = await client.hentInstitutionAsync({
    instnr: institutionId,
  })

  return schemas.institution.parse(response.institution)
}
