<?php

use Drupal\bnf_server\Hook\ViewsHooks;
use Drupal\bnf_server\Hook\ThemeHooks;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\views\ViewExecutable;

/*
 * The following hook functions is for Drupal 10, they can be removed, together
 * with the hook class service in `bnf_server.services.yml` when upgrading to
 * Drupal 11.
 */

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function bnf_server_theme(): array {
  return \Drupal::service(ThemeHooks::class)->theme();
}

/**
 * Implements hook_preprocess_HOOK().
 */
#[LegacyHook]
function bnf_server_preprocess_page(array &$variables): void {
  \Drupal::service(ThemeHooks::class)->preprocessPage($variables);
}

/**
 * Implements hook_views_pre_build().
 *
 * Setting the allowed importable content types as contextual filter.
 */
#[LegacyHook]
function bnf_server_views_pre_build(ViewExecutable $view): void {
  \Drupal::service(ViewsHooks::class)->preBuild($view);
}
