<?php

/**
 * @file
 * Contains dpl_library_agency.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\dpl_library_agency\Branch\FbsBranchRepository;
use Drupal\dpl_library_agency\Form\GeneralSettingsForm;
use Drupal\dpl_library_agency\GeneralSettings;
use Drupal\drupal_typed\DrupalTyped;
use Drupal\node\NodeForm;
use Drupal\node\NodeInterface;
use Drupal\dpl_react_apps\Controller\DplReactAppsController;

/**
 * Implements hook_dpl_protected_nodes_get_protected_nodes().
 */
function dpl_library_agency_dpl_protected_nodes_get_protected_nodes(): array {
  return dpl_protected_nodes_get_context(GeneralSettingsForm::class, 'dpl_library_agency.general_settings');

}

/**
 * Implements hook_preprocess_page().
 */
function dpl_library_agency_preprocess_page(array &$variables): void {
  $config = \Drupal::config('dpl_library_agency.general_settings');
  $variables['opening_hours_url'] = $config->get('opening_hours_url') ?? GeneralSettings::OPENING_HOURS_URL;
}

/**
 * Used as dynamic list options (allowed_values_function) for a field.
 *
 * See field.storage.node.field_agency_branch_id.yml for more info.
 *
 * @return array<string, string>
 *   The options, used in field_agency_branch_id dropdown.
 */
function dpl_library_agency_field_agency_branch_id_options(): array {
  $options = [];

  try {
    $repository = DrupalTyped::service(FbsBranchRepository::class, 'dpl_library_agency.branch.repository.fbs');
    $branches = $repository->getBranches();

    foreach ($branches as $branch) {
      $options[$branch->id] = "$branch->originalTitle ($branch->id)";
    }

    return $options;
  }
  catch (\Exception) {
    return [];
  }
}

/**
 * Implements hook_form_alter().
 *
 * Adding a custom validator to branch node forms.
 *
 * @see dpl_library_agency_validate_branch_node()
 */
function dpl_library_agency_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  if (!in_array($form_id, ['node_branch_edit_form', 'node_branch_form'])) {
    return;
  }

  $form['#validate'][] = 'dpl_library_agency_validate_branch_node';
}

/**
 * Validating the branch node edit/add forms.
 *
 * Making sure that any agency branch ID inputted is not used by any other
 * nodes.
 *
 * @param array<mixed> $form
 *   See dpl_library_agency_form_alter().
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   See dpl_library_agency_form_alter().
 */
function dpl_library_agency_validate_branch_node(array &$form, FormStateInterface $form_state): void {
  $form_object = $form_state->getFormObject();

  if (!($form_object instanceof NodeForm)) {
    return;
  }

  $user_input = $form_state->getUserInput();
  $branch_id = $user_input['field_agency_branch_id'] ?? NULL;

  if (empty($branch_id)) {
    return;
  }

  $current_node = $form_object->getEntity();

  if (!($current_node instanceof NodeInterface)) {
    return;
  }

  $node_storage = \Drupal::entityTypeManager()->getStorage('node');

  /** @var \Drupal\node\NodeInterface[] $used_nodes */
  $used_nodes = $node_storage->loadByProperties([
    'field_agency_branch_id' => $branch_id,
  ]);

  foreach ($used_nodes as $used_node) {
    if ($used_node->id() !== $current_node->id()) {

      $form_state->setErrorByName(
        'field_agency_branch_id',
        t('This agency branch ID is already in use by @title', ['@title' => $used_node->label()], ['context' => 'dpl_library_agency']),
      );
      return;
    }
  }

}

/**
 * Implements hook_preprocess_html().
 */
function dpl_library_agency_preprocess_html(array &$variables): void {
  $config = \Drupal::config('dpl_library_agency.general_settings');
  if ($config->get('use_lms_user_api')) {
    $variables['attributes']['data-lms-user-api-enabled'] = 'true';
  }
  if ($config->get('show_search_branch_selection')) {
    $variables['attributes']['data-show-search-branch-selection'] = 'true';

    // Build configurations for blacklisted search branches and all branches.
    $branchSettings = \Drupal::service('dpl_library_agency.branch_settings');
    $blacklistedSearchBranchesConfig = DplReactAppsController::buildBranchesListProp($branchSettings->getExcludedSearchBranches());
    $variables['attributes']['data-blacklisted-search-branches-config'] = $blacklistedSearchBranchesConfig;
  }
  if ($config->get('show_cicero_lms_search_sorting')) {
    $variables['attributes']['data-show-search-sorting'] = 'true';
  }
  if ($config->get('search_lazy_types_loading')) {
    $variables['attributes']['data-search-lazy-types-loading'] = 'true';
  }
}

/**
 * Implements hook_dpl_react_apps_data().
 */
function dpl_library_agency_dpl_react_apps_data(array &$data): void {
  $data['texts'] += [
    'search-in-all-branches' => t('Search in all branches'),
  ];
}

