/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type CampaignMatchPOSTBodyFacetsItemValuesItem = {
  key?: string;
  term?: string;
  score?: number;
};
