/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CampaignMatchPOST_Format } from "./campaignMatchPOSTFormat";

export type CampaignMatchPOSTParams = {
  /**
   * Request format
   */
  _format?: CampaignMatchPOST_Format;
};
