/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type CampaignMatchPOST_Format =
  (typeof CampaignMatchPOST_Format)[keyof typeof CampaignMatchPOST_Format];

export const CampaignMatchPOST_Format = {
  json: "json"
} as const;
