/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CurrentEventsGET200ItemAddress } from "./currentEventsGET200ItemAddress";
import type { CurrentEventsGET200ItemDateTime } from "./currentEventsGET200ItemDateTime";
import type { CurrentEventsGET200ItemExternalData } from "./currentEventsGET200ItemExternalData";
import type { CurrentEventsGET200ItemImage } from "./currentEventsGET200ItemImage";
import type { CurrentEventsGET200ItemOriginalImage } from "./currentEventsGET200ItemOriginalImage";
import type { CurrentEventsGET200ItemSeries } from "./currentEventsGET200ItemSeries";
import type { CurrentEventsGET200ItemState } from "./currentEventsGET200ItemState";
import type { CurrentEventsGET200ItemTeaserImage } from "./currentEventsGET200ItemTeaserImage";
import type { CurrentEventsGET200ItemTicketCategoriesItem } from "./currentEventsGET200ItemTicketCategoriesItem";

export type CurrentEventsGET200Item = {
  /** A unique identifier for the event. */
  uuid: string;
  /** The event title. */
  title: string;
  /** The short event description. */
  description?: string;
  /** An absolute URL end users should use to view the event at the website. */
  url: string;
  /** When the event was created. In ISO 8601 format. */
  created_at: string;
  /** When the event was last updated. In ISO 8601 format. */
  updated_at: string;
  /** Whether the event is marked as relevant for ticket management systems */
  ticket_manager_relevance?: boolean;
  /** The main image for the event. (Scaled) */
  image?: CurrentEventsGET200ItemImage;
  /** The main image for the event. (Original source) */
  originalImage?: CurrentEventsGET200ItemOriginalImage;
  /** The uniform teaser image for the event. */
  teaserImage?: CurrentEventsGET200ItemTeaserImage;
  /** The state of the event. */
  state: CurrentEventsGET200ItemState;
  /** Whether the event is marked as an all-day event, without time relevance. */
  all_day?: boolean;
  /** When the event occurs. */
  date_time: CurrentEventsGET200ItemDateTime;
  /** The associated library branches. */
  branches?: string[];
  /** Where the event occurs. */
  address?: CurrentEventsGET200ItemAddress;
  /** The categories associated with the event. */
  categories?: string[];
  /** The audiences associated with the event. */
  audiences?: string[];
  /** The tags associated with the event. */
  tags?: string[];
  /** The partners associated with the event. */
  partners?: string[];
  /** Ticket categories used for the event. Not present for events without ticketing. */
  ticket_categories?: CurrentEventsGET200ItemTicketCategoriesItem[];
  /** Total number of tickets which can be sold for the event. */
  ticket_capacity?: number;
  /** An event may be part of a series. One example of this is recurring events. */
  series?: CurrentEventsGET200ItemSeries;
  /** An editorial WYSIWYG/HTML description of the event. */
  body?: string;
  /** Data for the event provided by a third party. */
  external_data?: CurrentEventsGET200ItemExternalData;
  /** The screens this event should be shown on. */
  screen_names?: string[];
};
