/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CurrentEventsGET_Format } from "./currentEventsGETFormat";

export type CurrentEventsGETParams = {
  /**
   * Request format
   */
  _format?: CurrentEventsGET_Format;
};
