/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type CurrentEventsGET_Format =
  (typeof CurrentEventsGET_Format)[keyof typeof CurrentEventsGET_Format];

export const CurrentEventsGET_Format = {
  json: "json"
} as const;
