/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * If an event is physical or not.
 */
export type CurrentEventsGET200ItemAddressLocationType =
  (typeof CurrentEventsGET200ItemAddressLocationType)[keyof typeof CurrentEventsGET200ItemAddressLocationType];

export const CurrentEventsGET200ItemAddressLocationType = {
  physical: "physical",
  online: "online"
} as const;
