/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The state of the event.
 */
export type CurrentEventsGET200ItemState =
  (typeof CurrentEventsGET200ItemState)[keyof typeof CurrentEventsGET200ItemState];

export const CurrentEventsGET200ItemState = {
  TicketSaleNotOpen: "TicketSaleNotOpen",
  Active: "Active",
  SoldOut: "SoldOut",
  Cancelled: "Cancelled",
  Occurred: "Occurred"
} as const;
