/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursCreatePOSTBodyCategory = {
  title: string;
  /** A CSS compatible color code which can be used to represent the category */
  color: string;
};
