/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursCreatePOST_Format =
  (typeof DplOpeningHoursCreatePOST_Format)[keyof typeof DplOpeningHoursCreatePOST_Format];

export const DplOpeningHoursCreatePOST_Format = {
  json: "json"
} as const;
