/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursLegacyListGET_Format =
  (typeof DplOpeningHoursLegacyListGET_Format)[keyof typeof DplOpeningHoursLegacyListGET_Format];

export const DplOpeningHoursLegacyListGET_Format = {
  json: "json"
} as const;
