/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { DplOpeningHoursListGET_Format } from "./dplOpeningHoursListGETFormat";

export type DplOpeningHoursListGETParams = {
  /**
   * Request format
   */
  _format?: DplOpeningHoursListGET_Format;
  /**
   * The id of the branch for which to retrieve opening hours.
   */
  branch_id?: number;
  /**
   * Retrieve opening hours which occur after and including the provided date. In ISO 8601 format.
   */
  from_date?: string;
  /**
   * Retrieve opening hours which occur before and including the provided date. In ISO 8601 format.
   */
  to_date?: string;
};
