/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursListGET_Format =
  (typeof DplOpeningHoursListGET_Format)[keyof typeof DplOpeningHoursListGET_Format];

export const DplOpeningHoursListGET_Format = {
  json: "json"
} as const;
