/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type EventPATCH_Format =
  (typeof EventPATCH_Format)[keyof typeof EventPATCH_Format];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventPATCH_Format = {
  json: "json"
} as const;
