/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The state of the event.
 */
export type EventPATCHBodyState =
  (typeof EventPATCHBodyState)[keyof typeof EventPATCHBodyState];

export const EventPATCHBodyState = {
  TicketSaleNotOpen: "TicketSaleNotOpen",
  Active: "Active",
  SoldOut: "SoldOut",
  Cancelled: "Cancelled",
  Occurred: "Occurred"
} as const;
