/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The library branch responsible for the event. Unlike address, this describes who arranges the event - not where it takes place. The two differ when an event is held outside the library.
 */
export type EventsGET200ItemOrganizer = {
  /** A unique identifier for the organizer. It is stable across updates, and unique across libraries. */
  id: string;
  /** The name of the branch arranging the event. */
  name: string;
  /** An absolute URL for the page describing the branch. */
  url?: string;
  /** Street name and number of the branch. */
  street?: string;
  /** Zip code of the branch. */
  zip_code?: number;
  /** City of the branch. */
  city?: string;
  /** Country code in ISO 3166-1 alpha-2 format. E.g. DK for Denmark. */
  country?: string;
  /** Phone number of the branch. */
  phone?: string;
  /** Email address of the branch. */
  email?: string;
};
