/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventsGET200ItemTicketCategoriesItemPrice } from "./eventsGET200ItemTicketCategoriesItemPrice";

export type EventsGET200ItemTicketCategoriesItem = {
  /** A unique identifier for the ticket category. */
  uuid?: string;
  /** The name of the ticket category. */
  title: string;
  /** The price of a ticket in the category */
  price: EventsGET200ItemTicketCategoriesItemPrice;
};
