/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventsGET200ItemImage } from "./eventsGET200ItemImage";
import type { EventsGET200ItemOriginalImage } from "./eventsGET200ItemOriginalImage";
import type { EventsGET200ItemTeaserImage } from "./eventsGET200ItemTeaserImage";
import type { EventsGET200ItemState } from "./eventsGET200ItemState";
import type { EventsGET200ItemDateTime } from "./eventsGET200ItemDateTime";
import type { EventsGET200ItemAddress } from "./eventsGET200ItemAddress";
import type { EventsGET200ItemTicketCategoriesItem } from "./eventsGET200ItemTicketCategoriesItem";
import type { EventsGET200ItemSeries } from "./eventsGET200ItemSeries";
import type { EventsGET200ItemExternalData } from "./eventsGET200ItemExternalData";

export type EventsGET200Item = {
  /** A unique identifier for the event. */
  uuid: string;
  /** The event title. */
  title: string;
  /** The short event description. */
  description?: string;
  /** An absolute URL end users should use to view the event at the website. */
  url: string;
  /** When the event was created. In ISO 8601 format. */
  created_at: string;
  /** When the event was last updated. In ISO 8601 format. */
  updated_at: string;
  /** Whether the event is marked as relevant for ticket management systems */
  ticket_manager_relevance?: boolean;
  /** The main image for the event. (Scaled) */
  image?: EventsGET200ItemImage;
  /** The main image for the event. (Original source) */
  originalImage?: EventsGET200ItemOriginalImage;
  /** The uniform teaser image for the event. */
  teaserImage?: EventsGET200ItemTeaserImage;
  /** The state of the event. */
  state: EventsGET200ItemState;
  /** Whether the event is marked as an all-day event, without time relevance. */
  all_day?: boolean;
  /** When the event occurs. */
  date_time: EventsGET200ItemDateTime;
  /** The associated library branches. */
  branches?: string[];
  /** Where the event occurs. */
  address?: EventsGET200ItemAddress;
  /** The categories associated with the event. */
  categories?: string[];
  /** The tags associated with the event. */
  tags?: string[];
  /** The partners associated with the event. */
  partners?: string[];
  /** Ticket categories used for the event. Not present for events without ticketing. */
  ticket_categories?: EventsGET200ItemTicketCategoriesItem[];
  /** Total number of tickets which can be sold for the event. */
  ticket_capacity?: number;
  /** An event may be part of a series. One example of this is recurring events. */
  series?: EventsGET200ItemSeries;
  /** An editorial WYSIWYG/HTML description of the event. */
  body?: string;
  /** Data for the event provided by a third party. */
  external_data?: EventsGET200ItemExternalData;
  /** The screens this event should be shown on. */
  screen_names?: string[];
};
