/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * If an event is physical or not.
 */
export type EventsGET200ItemAddressLocationType =
  (typeof EventsGET200ItemAddressLocationType)[keyof typeof EventsGET200ItemAddressLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventsGET200ItemAddressLocationType = {
  physical: "physical",
  online: "online"
} as const;
