/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventPATCHBodyState } from "./eventPATCHBodyState";
import type { EventPATCHBodyExternalData } from "./eventPATCHBodyExternalData";

export type EventPATCHBody = {
  /** The state of the event. */
  state?: EventPATCHBodyState;
  /** Data for the event provided by a third party. */
  external_data?: EventPATCHBodyExternalData;
};
