/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type EventsGET_Format =
  (typeof EventsGET_Format)[keyof typeof EventsGET_Format];

export const EventsGET_Format = {
  json: "json"
} as const;
