/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type HappeningEventsGET_Format =
  (typeof HappeningEventsGET_Format)[keyof typeof HappeningEventsGET_Format];

export const HappeningEventsGET_Format = {
  json: "json"
} as const;
