/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * If an event is physical or not.
 */
export type HappeningEventsGET200ItemAddressLocationType =
  (typeof HappeningEventsGET200ItemAddressLocationType)[keyof typeof HappeningEventsGET200ItemAddressLocationType];

export const HappeningEventsGET200ItemAddressLocationType = {
  physical: "physical",
  online: "online"
} as const;
