/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { HappeningEventsGET_Format } from "./happeningEventsGETFormat";

export type HappeningEventsGETParams = {
  /**
   * Request format
   */
  _format?: HappeningEventsGET_Format;
};
