/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type ProxyUrlGET_Format =
  (typeof ProxyUrlGET_Format)[keyof typeof ProxyUrlGET_Format];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProxyUrlGET_Format = {
  json: "json"
} as const;
