/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { ProxyUrlGET200Data } from "./proxyUrlGET200Data";

export type ProxyUrlGET200 = {
  data?: ProxyUrlGET200Data;
};
