export const cyKeys = {
  "go-logo": "go-logo",
  "search-input": "search-input",
  "work-card": "work-card",
  "work-card-title": "work-card-title",
  "filters-button": "filters-button",
  "filter-button": "filter-button",
  "material-slider": "material-slider",
  "material-slider-skeleton": "material-slider-skeleton",
  "material-slider-prev-button": "material-slider-prev-button",
  "material-slider-next-button": "material-slider-next-button",
  "video-bundle": "video-bundle",
  "video-bundle-slider": "video-bundle-slider",
  "video-bundle-prev-button": "video-bundle-prev-button",
  "video-bundle-next-button": "video-bundle-next-button",
  "profile-button": "profile-button",
  "global-sheet": "global-sheet",
  "global-sheet-close-button": "global-sheet-close-button",
  "global-drawer": "global-drawer",
  "global-drawer-overlay": "global-drawer-overlay",
  "login-sheet-unilogin-button": "login-sheet-unilogin-button",
  "login-sheet-adgangsplatformen-button": "login-sheet-adgangsplatformen-button",
  "loan-login-modal": "loan-login-modal",
  "loan-login-modal-unilogin-button": "loan-login-modal-unilogin-button",
  "loan-login-modal-adgangsplatformen-button": "loan-login-modal-adgangsplatformen-button",
  "loan-material-modal": "loan-material-modal",
  "reservation-login-modal": "reservation-login-modal",
  "reservation-unilogin-modal": "reservation-unilogin-modal",
  "reservation-modal": "reservation-modal",
  "work-page-button-logged-in": "work-page-button-logged-in",
  "logout-button": "logout-button",
  "loan-slider": "loan-slider",
  "loan-slider-work": "loan-slider-work",
  "loan-slider-prev-button": "loan-slider-prev-button",
  "loan-slider-next-button": "loan-slider-next-button",
  "physical-loan-slider": "physical-loan-slider",
  "physical-loan-slider-work": "physical-loan-slider-work",
  "physical-loan-slider-prev-button": "physical-loan-slider-prev-button",
  "physical-loan-slider-next-button": "physical-loan-slider-next-button",
  "renew-loan-button": "renew-loan-button",
  "loan-details-modal": "loan-details-modal",
  "approve-renew-loan-button": "approve-renew-loan-button",
  "renew-loan-receipt": "renew-loan-receipt",
  "digital-loans-modal": "digital-loans-modal",
  "physical-loans-modal": "physical-loans-modal",
  "reservations-modal": "reservations-modal",
  "reservation-details": "reservation-details",
  "view-all-physical-loans-button": "view-all-physical-loans-button",
  "view-all-reservations-button": "view-all-reservations-button",
  "fees-modal": "fees-modal",
  "compensation-modal": "compensation-modal",
  "profile-notifications": "profile-notifications",
  "profile-notification": "profile-notification",
  "profile-notification-button": "profile-notification-button",
  "profile-notifications-empty": "profile-notifications-empty",
  "profile-notifications-error": "profile-notifications-error",
  "read-loan-button": "read-loan-button",
  "listen-loan-button": "listen-loan-button",
  "modal-back-button": "modal-back-button",
  "view-all-digital-loans-button": "view-all-digital-loans-button",
  "renew-loan-receipt-due-date": "renew-loan-receipt-due-date",
  "slide-select-option": "slide-select-option",
  "try-ebook-button": "try-ebook-button",
  "loan-button": "loan-button",
  "approve-loan-button": "approve-loan-button",
  "reserve-button": "reserve-button",
  "approve-reservation-button": "approve-reservation-button",
  "reservation-receipt": "reservation-receipt",
  "reservation-receipt-queue-position": "reservation-receipt-queue-position",
  "reservation-receipt-pickup-branch": "reservation-receipt-pickup-branch",
  "loan-already-loaned": "loan-already-loaned",
  "view-loan-button": "view-loan-button",
  "view-reservation-button": "view-reservation-button",
  "delete-reservation-button": "delete-reservation-button",
  "delete-reservation-modal": "delete-reservation-modal",
  "delete-reservation-receipt": "delete-reservation-receipt",
  "approve-delete-reservation-button": "approve-delete-reservation-button",
} as const

export type CyKey = keyof typeof cyKeys

// Define viewport configurations
export const viewports = {
  mobile: {
    width: 375,
    height: 667,
  },
  desktop: {
    width: 1280,
    height: 720,
  },
} as const

export type ViewportType = keyof typeof viewports
