<?php

/**
 * @file
 * Branch Opening Hours logic.
 */

/**
 * Implements hook_theme().
 */
function eonext_branch_opening_hours_theme($existing, $type, $theme, $path) {
  return [
    'html__node__opening_hours_bare' => [
      'base hook' => 'html',
    ],
    'page__node__opening_hours_bare' => [
      'base hook' => 'page',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Provide a bare html theme suggestion.
 */
function eonext_branch_opening_hours_theme_suggestions_html(array $variables): array {
  $suggestions = [];
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ('eonext_branch_opening_hours.node_bare' === $route_name) {
    $suggestions[] = 'html__node__opening_hours_bare';
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Provide a bare page theme suggestion.
 */
function eonext_branch_opening_hours_theme_suggestions_page(array $variables): array {
  $suggestions = [];
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ('eonext_branch_opening_hours.node_bare' === $route_name) {
    $suggestions[] = 'page__node__opening_hours_bare';
  }

  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_html__node__opening_hours_bare(array &$variables): void {
  /** @var \Drupal\node\NodeInterface $branch_node */
  $branch_node = \Drupal::routeMatch()->getParameter('node');

  $variables['attributes']['class'][] = 'opening-hours--bare';
  $variables['head_title'] = t(
    '@library_name | Opening Hours',
    ['@library_name' => $branch_node->getTitle()],
    ['context' => 'eonext']
  );
}
