/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

/**
 * A collection identifier in the form "work-of:<digits>-<alphanum>:<alphanum>".
 * @pattern ^work-of:\d+-\w+:\w+$
 */
export type ItemId = string;
