/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */
import type { ListId } from "./listId";
import type { ItemId } from "./itemId";

export interface List {
  id: ListId;
  collections: ItemId[];
}
