/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */
import type { ItemId } from "./itemId";
import type { ListId } from "./listId";

export interface List {
  id: ListId;
  collections: ItemId[];
}
