/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

export type VersionParameter =
  (typeof VersionParameter)[keyof typeof VersionParameter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VersionParameter = {
  NUMBER_2: 2
} as const;
