/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface Address {
  city: string;
  country: string;
  postalCode: string;
  /** Street and number */
  street: string;
}
