/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AgencyLocation {
  /** Location identifier */
  locationId: string;
  /** Name of the location */
  title: string;
}
