/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronV4 } from "./patronV4";

export interface AuthenticatedPatronV4 {
  /**
   * True if patron successfully authenticated.
   *  If false then either the user is not known in the FBS, or an invalid combination of authentication parameters
   *  has been used.
   */
  authenticated: boolean;
  /** Only available if patron exists in FBS and was succesfully authenticated. */
  patron?: PatronV4;
}
