/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Period } from "./period";

export interface BookingInfo {
  /** The booking period information containing the start and the end date */
  period: Period;
  /** The preferred number of materials */
  preferredMaterials: number;
}
