/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { MaterialGroup } from "./materialGroup";
import type { Periodical } from "./periodical";

export interface FeeMaterialV2 {
  /** The material group that the material belongs to */
  materialGroup: MaterialGroup;
  /** Identifies the exact material covered by the fee */
  materialItemNumber: string;
  /** Present if material is a periodical */
  periodical?: Periodical;
  /** The FAUST number of the bibliographic record */
  recordId: string;
}
