/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { AgencyBranch } from "./agencyBranch";
import type { AgencyDepartment } from "./agencyDepartment";
import type { AgencyLocation } from "./agencyLocation";
import type { AgencySection } from "./agencySection";
import type { AgencySublocation } from "./agencySublocation";
import type { MaterialV4 } from "./materialV4";

export interface HoldingsV5 {
  /** Placement branch */
  branch: AgencyBranch;
  /** Placement department */
  department?: AgencyDepartment;
  /** Placement location */
  location?: AgencyLocation;
  /** Materials that belongs to this placement */
  materials: MaterialV4[];
  /** Placement section */
  section?: AgencySection;
  /** Placement sublocation */
  sublocation?: AgencySublocation;
}
