/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { AgencyBranch } from "./agencyBranch";
import type { AgencyDepartment } from "./agencyDepartment";
import type { AgencyLocation } from "./agencyLocation";
import type { AgencySublocation } from "./agencySublocation";
import type { MaterialV3 } from "./materialV3";

export interface HoldingsV3 {
  /** Placement branch */
  branch: AgencyBranch;
  /** Placement department */
  department?: AgencyDepartment;
  /** Placement location */
  location?: AgencyLocation;
  /** Materials that belongs to this placement */
  materials: MaterialV3[];
  /** Placement sublocation */
  sublocation?: AgencySublocation;
}
