/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { AgencyBranch } from "./agencyBranch";
import type { MaterialV4 } from "./materialV4";
import type { PlacementV1 } from "./placementV1";

export interface HoldingsLogisticsV2 {
  /** Placement branch */
  branch: AgencyBranch;
  /** LMS placement */
  lmsPlacement?: PlacementV1;
  /** Logistics placement */
  logisticsPlacement?: string[];
  /** Materials that belongs to this placement */
  materials: MaterialV4[];
}
