/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface InterestV1 {
  /** Display name of the interest */
  displayName: string;
  /** Name of the interest */
  name: string;
}
