/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { ILLBibliographicRecord } from "./iLLBibliographicRecord";
import type { Periodical } from "./periodical";

export interface LoanDetails {
  /** The date when the material must be returned */
  dueDate: string;
  /** Additional bibliographic information for inter-library loans */
  ilBibliographicRecord?: ILLBibliographicRecord;
  /** The date when the material was picked up */
  loanDate: string;
  /** Identifies the loan for use when renewing the loan */
  loanId: number;
  /** The loan type, either <b>loan</b> or <b>interLibraryLoan</b> */
  loanType: string;
  /** Name of the material group that the material belongs to */
  materialGroupName: string;
  /** Identifies the exact material that has been loaned */
  materialItemNumber: string;
  /** Present if material is a periodical */
  periodical?: Periodical;
  /** The FAUST number of the bibliographic record */
  recordId: string;
}
