/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { MaterialGroup } from "./materialGroup";
import type { Periodical } from "./periodical";

export interface MaterialV3 {
  /** True if material is available on-shelf, false if lent out */
  available: boolean;
  /** Identifies the material */
  itemNumber: string;
  /** Name of the material group that the material belongs to */
  materialGroup: MaterialGroup;
  /** Present if material is a periodical */
  periodical?: Periodical;
}
