/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PeriodicalReservation } from "./periodicalReservation";
import type { ReservationDetailsV4 } from "./reservationDetailsV4";

export interface ReservationResultV4 {
  /** Periodical information of the reservation */
  periodical?: PeriodicalReservation;
  /** Recordid of the record to reserve */
  recordId: string;
  /** The reservation data as returned by the create/update operation */
  reservationDetails?: ReservationDetailsV4;
  /** The reservation result */
  result: string;
}
