/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV6 } from "./patronSettingsV6";
import type { PincodeChange } from "./pincodeChange";

export interface UpdatePatronRequestV6 {
  /** Set this if patron details are to be changed */
  patron?: PatronSettingsV6;
  /** Set this if pincode is to be changed */
  pincodeChange?: PincodeChange;
}
