/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { UpdateReservation } from "./updateReservation";

export interface UpdateReservationBatch {
  reservations: UpdateReservation[];
}
