/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV3 } from "./patronSettingsV3";
import type { PincodeChange } from "./pincodeChange";

export interface UpdatePatronRequestV3 {
  /** Set this if patron details are to be changed */
  patron?: PatronSettingsV3;
  /** Set this if pincode is to be changed */
  pincodeChange?: PincodeChange;
}
