<?php

use Drupal\bnf\Hook\EntityHooks;
use Drupal\bnf\Hook\GraphQLComposeHooks;
use Drupal\bnf\Hook\PageHooks;
use Drupal\bnf\Hook\ThemeHooks;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;

/*
 * The following hook functions is for Drupal 10, they can be removed, together
 * with the hook class service in `bnf.services.yml` when upgrading to Drupal
 * 11.
 */

/**
 * Implements theme_preprocess_html().
 */
#[LegacyHook]
function bnf_preprocess_html(array &$variables): void {
  \Drupal::service(ThemeHooks::class)->preprocessHtml($variables);
}

/**
 * Implements hook_entity_base_field_info().
 *
 * @return \Drupal\Core\Field\FieldDefinitionInterface[]
 *   The field definitions.
 */
#[LegacyHook]
function bnf_entity_base_field_info(EntityTypeInterface $entity_type): array {
  return \Drupal::service(EntityHooks::class)->baseFields($entity_type);
}

/**
 * Implements hook_page_attachments().
 *
 * @param mixed[] $page
 *   The page render array.
 */
#[LegacyHook]
function bnf_page_attachments(array &$page): void {
  \Drupal::service(PageHooks::class)->pageAttachments($page);
}

/**
 * Implements hook_graphql_compose_field_type_alter().
 *
 * @phpstan-ignore missingType.iterableValue
 */
#[LegacyHook]
function bnf_graphql_compose_field_type_alter(array &$field_types): void {
  \Drupal::service(GraphQLComposeHooks::class)->extendLinkType($field_types);
}
