"""
A mobile app category.
"""
type AppCategory {
  id: String!
  title: String!
  icon: String!
  elements: [AppContentElement!]!
}

"""
Type of app.
"""
enum AppType {
  MYBIBLO
  BIBLO
  BIBLOGO
}

"""
Orientation of the video.
"""
enum AppVideoOrientation {
  HORIZONTAL
  VERTICAL
}

"""
A video, for the app.
"""
type AppVideo {
  url: String!
  thumbnail: String!
  orientation: AppVideoOrientation!
}

"""
An AppContentElement.

This is an app mapping of Paragraphs.
"""
interface AppContentElement {
  id: String!
}

"""
A text content element.
"""
type AppContentElementText implements AppContentElement {
  id: String!
  body: String!
}

"""
A video element.
"""
type AppContentElementVideo implements AppContentElement {
  id: String!
  title: String
  video: AppVideo!
}

"""
A bundle with a video and manually selected materials.
"""
type AppContentElementVideoBundleManual implements AppContentElement {
  id: String!
  title: String!
  workIds: [String!]!
  video: AppVideo!
}

"""
A bundle with a video and a material search string.
"""
type AppContentElementVideoBundleAutomatic implements AppContentElement {
  id: String!
  title: String!
  cql: String!
  limit: Int!
  video: AppVideo!
}

"""
A navigation spots element with manually selected content.
"""
type AppContentElementNavSpotsManual implements AppContentElement {
  id: String!
  linkedPages: [String!]!
}

"""
A recommendation element.
"""
type AppContentElementRecommendation implements AppContentElement {
  id: String!
  imagePositionRight: Boolean!
  title: String
  description: String
  workId: String!
}

"""
A material slider with automatically selected materials based on a CQL search.
"""
type AppContentElementGoMaterialSliderAutomatic implements AppContentElement {
  id: String!
  title: String!
  cql: String!
  limit: Int!
}

"""
A material slider with manually selected materials.
"""
type AppContentElementGoMaterialSliderManual implements AppContentElement {
  id: String!
  title: String!
  workIds: [String!]!
}

"""
A material grid with automatically selected materials based on a CQL search.
"""
type AppContentElementMaterialGridAutomatic implements AppContentElement {
  id: String!
  title: String
  description: String
  cql: String!
  limit: Int!
  priorityMaterialType: String
}

"""
A material grid with manually selected materials.
"""
type AppContentElementMaterialGridManual implements AppContentElement {
  id: String!
  title: String
  description: String
  workIds: [String!]!
}

"""
A linkbox element.
"""
type AppContentElementGoLinkbox implements AppContentElement {
  id: String!
  title: String!
  color: String
  description: String!
  image: String
  contentId: String!
}
