eonext_react.settings:
  type: config_object
  label: 'React settings'
  mapping:
    langcode:
      type: langcode
      label: 'Language code'
    javascript:
      type: text
      label: 'JavaScript injected into non-administrative pages'
