<?php
/**
 * EventsGET200ResponseInnerOrganizer
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * DPL CMS - REST API
 *
 * The REST API provided by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace DanskernesDigitaleBibliotek\CMS\Api\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the EventsGET200ResponseInnerOrganizer model.
 *
 * The library branch responsible for the event. Unlike address, this describes who arranges the event - not where it takes place. The two differ when an event is held outside the library.
 *
 * @package DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author  OpenAPI Generator team
 */

class EventsGET200ResponseInnerOrganizer 
{
        /**
     * A unique identifier for the organizer. It is stable across updates, and unique across libraries.
     *
     * @var string|null
     * @SerializedName("id")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $id = null;

    /**
     * The name of the branch arranging the event.
     *
     * @var string|null
     * @SerializedName("name")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $name = null;

    /**
     * An absolute URL for the page describing the branch.
     *
     * @var string|null
     * @SerializedName("url")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $url = null;

    /**
     * Street name and number of the branch.
     *
     * @var string|null
     * @SerializedName("street")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $street = null;

    /**
     * Zip code of the branch.
     *
     * @var int|null
     * @SerializedName("zip_code")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $zipCode = null;

    /**
     * City of the branch.
     *
     * @var string|null
     * @SerializedName("city")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $city = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format. E.g. DK for Denmark.
     *
     * @var string|null
     * @SerializedName("country")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $country = null;

    /**
     * Phone number of the branch.
     *
     * @var string|null
     * @SerializedName("phone")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $phone = null;

    /**
     * Email address of the branch.
     *
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->name = array_key_exists('name', $data) ? $data['name'] : $this->name;
            $this->url = array_key_exists('url', $data) ? $data['url'] : $this->url;
            $this->street = array_key_exists('street', $data) ? $data['street'] : $this->street;
            $this->zipCode = array_key_exists('zipCode', $data) ? $data['zipCode'] : $this->zipCode;
            $this->city = array_key_exists('city', $data) ? $data['city'] : $this->city;
            $this->country = array_key_exists('country', $data) ? $data['country'] : $this->country;
            $this->phone = array_key_exists('phone', $data) ? $data['phone'] : $this->phone;
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
        }
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param string|null $id  A unique identifier for the organizer. It is stable across updates, and unique across libraries.
    *
    * @return $this
    */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
    * Sets name.
    *
    * @param string|null $name  The name of the branch arranging the event.
    *
    * @return $this
    */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }




    /**
     * Gets url.
     *
     * @return string|null
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
    * Sets url.
    *
    * @param string|null $url  An absolute URL for the page describing the branch.
    *
    * @return $this
    */
    public function setUrl(?string $url = null): self
    {
        $this->url = $url;

        return $this;
    }




    /**
     * Gets street.
     *
     * @return string|null
     */
    public function getStreet(): ?string
    {
        return $this->street;
    }

    /**
    * Sets street.
    *
    * @param string|null $street  Street name and number of the branch.
    *
    * @return $this
    */
    public function setStreet(?string $street = null): self
    {
        $this->street = $street;

        return $this;
    }




    /**
     * Gets zipCode.
     *
     * @return int|null
     */
    public function getZipCode(): ?int
    {
        return $this->zipCode;
    }

    /**
    * Sets zipCode.
    *
    * @param int|null $zipCode  Zip code of the branch.
    *
    * @return $this
    */
    public function setZipCode(?int $zipCode = null): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }




    /**
     * Gets city.
     *
     * @return string|null
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
    * Sets city.
    *
    * @param string|null $city  City of the branch.
    *
    * @return $this
    */
    public function setCity(?string $city = null): self
    {
        $this->city = $city;

        return $this;
    }




    /**
     * Gets country.
     *
     * @return string|null
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
    * Sets country.
    *
    * @param string|null $country  Country code in ISO 3166-1 alpha-2 format. E.g. DK for Denmark.
    *
    * @return $this
    */
    public function setCountry(?string $country = null): self
    {
        $this->country = $country;

        return $this;
    }




    /**
     * Gets phone.
     *
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
    * Sets phone.
    *
    * @param string|null $phone  Phone number of the branch.
    *
    * @return $this
    */
    public function setPhone(?string $phone = null): self
    {
        $this->phone = $phone;

        return $this;
    }




    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
    * Sets email.
    *
    * @param string|null $email  Email address of the branch.
    *
    * @return $this
    */
    public function setEmail(?string $email = null): self
    {
        $this->email = $email;

        return $this;
    }



}


