const materialTypes = {
  "materialtypes.sortpriority": [
    "EBOOK",
    "BOOK_ELECTRONIC",
    "PICTURE_BOOK_ELECTRONIC",
    "PICTURE_BOOK_ONLINE",
    "GRAPHIC_NOVEL_ONLINE",
    "GRAPHIC_NOVEL_ELECTRONIC",
    "COMIC_ELECTRONIC",
    "COMIC_ONLINE",
    "AUDIO_BOOK_ONLINE",
    "BOOK",
    "PICTURE_BOOK",
    "COMIC",
    "GRAPHIC_NOVEL",
    "PODCAST",
  ] as string[],
  "materialtypes.translations": {
    BOOK: "Bog",
    EBOOK: "E-bog",
    BOOK_ELECTRONIC: "E-bog",
    GRAPHIC_NOVEL: "Graphic novel",
    GRAPHIC_NOVEL_ELECTRONIC: "E-graphic novel",
    GRAPHIC_NOVEL_ONLINE: "E-graphic novel",
    COMIC: "Tegneserie",
    COMIC_ELECTRONIC: "E-tegneserie",
    COMIC_ONLINE: "E-tegneserie",
    PICTURE_BOOK: "Billedbog",
    PICTURE_BOOK_ELECTRONIC: "E-billedbog",
    PICTURE_BOOK_ONLINE: "E-billedbog",
    AUDIO_BOOK_ONLINE: "Lydbog",
    PODCAST: "Podcast",
  } as { [key: string]: string },
  "materialtypes.facetTermMap": {
    BOOK: "bog",
    EBOOK: "e-bog",
    BOOK_ELECTRONIC: "e-bog",
    GRAPHIC_NOVEL: "graphic novel",
    GRAPHIC_NOVEL_ELECTRONIC: "graphic novel (elektronisk)",
    GRAPHIC_NOVEL_ONLINE: "graphic novel (online)",
    COMIC: "tegneserie",
    COMIC_ELECTRONIC: "tegneserie (elektronisk)",
    COMIC_ONLINE: "tegneserie (online)",
    PICTURE_BOOK: "billedbog",
    PICTURE_BOOK_ELECTRONIC: "billedbog (elektronisk)",
    PICTURE_BOOK_ONLINE: "billedbog (online)",
    AUDIO_BOOK_ONLINE: "lydbog (online)",
    PODCAST: "podcast",
  } as { [key: string]: string },
  "materialtypes.icons": {
    book: ["BOOK"],
    ebook: ["EBOOK", "BOOK_ELECTRONIC"],
    comic: ["COMIC", "GRAPHIC_NOVEL"],
    comicOnline: [
      "COMIC_ONLINE",
      "COMIC_ELECTRONIC",
      "GRAPHIC_NOVEL_ONLINE",
      "GRAPHIC_NOVEL_ELECTRONIC",
    ],
    pictureBook: ["PICTURE_BOOK"],
    pictureBookOnline: ["PICTURE_BOOK_ONLINE", "PICTURE_BOOK_ELECTRONIC"],
    audioBook: ["AUDIO_BOOK"],
    audioBookOnline: ["AUDIO_BOOK_ONLINE", "AUDIO_BOOK_ELECTRONIC"],
    podcast: ["PODCAST"],
  },
}

export default materialTypes
