block.settings.eonext_opening_hours_per_branch:
  type: block_settings
  label: 'Opening hours per branch block'
  mapping:
    available_branches:
      type: sequence
      label: Available branches
      sequence:
        type: integer
        label: The branch id

eonext_opening_hours.branch_expansion:
  type: config_object
  label: "EO Next Branch Expansion settings"
  mapping:
    expanded_branches:
      type: sequence
      label: "Expanded Branches"
      sequence:
        type: integer
        label: "Branch Node ID"
