<?php

declare(strict_types=1);

use Drupal\bnf_example_content\Hook\ModuleHooks;
use Drupal\Core\Hook\Attribute\LegacyHook;

/*
 * The following hook functions is for Drupal 10, they can be removed, together
 * with the hook class service in `bnf_example_content.services.yml` when
 * upgrading to Drupal 11.
 */

/**
 * Implements hook_modules_installed().
 *
 * @param string[] $modules
 *   The names of the modules that were installed.
 */
#[LegacyHook]
function bnf_example_content_modules_installed(array $modules): void {
  \Drupal::service(ModuleHooks::class)->modulesInstalled($modules);
}
