name: Design / GitHub Pages

on:
  push:
    branches:
      - develop
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-system
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm run css:build
      - run: pnpm run build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./design-system/storybook-static
          destination_dir: design-system
          # Don't wipe out other projects folder when deploying this.
          keep_files: true
