name: Design / Lint

on:
  pull_request:
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
  push:
    branches:
      - main
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'
      - pnpm-lock.yaml
      - pnpm-workspace.yaml

jobs:
  css-lint:
    name: Design / CSS Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run css:lint
        run: pnpm run css:lint
        working-directory: design-system

  js-lint:
    name: Design / JS Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run js:lint
        run: pnpm run js:lint
        working-directory: design-system

  markdown-linkt:
    name: Design / Markdown Linter
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run markdown:lint
        run: pnpm run markdown:lint
        working-directory: design-system
