name: Go / Chromatic

on:
  push:
    branches:
      - main
      - develop
      - release/*
    paths:
      - "go/**"
      - ".github/workflows/go-chromatic.yml"
  pull_request:
    paths:
      - "go/**"
      - ".github/workflows/go-chromatic.yml"
    types: [ready_for_review, opened, synchronize]

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    name: Go / Chromatic

    if: github.event_name == 'push' || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: "go/.nvmrc"

      - name: Load environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: "go/.env.test"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@v17
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_GO }}
          workingDir: go
          autoAcceptChanges: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
