name: Go / ESLint check

on:
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v6
        with:
          node-version-file: "go/.nvmrc"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Javascripts
        run: yarn lint
