---
name: React / Codegen

on:
  pull_request:
    paths:
      - 'react/**'
      - 'schemas/openapi/**'
      - 'schemas/graphql/dbc-fbi.temp-next.graphql'
      - 'cms/openapi.json'
      - '.github/workflows/react-codegen.yml'

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codegen:
    name: Generated clients
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'react/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'react/yarn.lock'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go-task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Codegen - DBC gateway GraphQL
        run: task codegen:dbc:gateway

      - name: Codegen - REST services
        run: task codegen:rest-services

      - name: Codegen - FBS client
        run: task codegen:client:fbs

      - name: Codegen - Publizon client
        run: task codegen:client:publizon

      - name: Codegen - dpl-cms client
        run: task codegen:client:dpl-cms

      - name: Ensure generated client code has not drifted
        run: git diff --exit-code
